import type {
  LicenseConfig,
  NavBarConfig,
  ProfileConfig,
  SiteConfig,
} from './types/config';
import { LinkPreset } from './types/config';

export const siteConfig: SiteConfig = {
  title: 'Toycube',
  subtitle: 'Blog',
  lang: 'en', // 'en', 'zh_CN', 'zh_TW', 'ja', 'ko'
  themeColor: {
    hue: 250, // Default hue for the theme color, from 0 to 360. e.g. red: 0, teal: 200, cyan: 250, pink: 345
    fixed: false, // Hide the theme color picker for visitors
  },
  banner: {
    enable: true,
    src: 'assets/images/demo-banner.png', // Relative to the /src directory. Relative to the /public directory if it starts with '/'
    position: 'center', // Equivalent to object-position, defaults center
    credit: {
      enable: true, // Display the credit text of the banner image
      text: '`Software Cube` generated by DeviantArt Dreamup for the daily challenge', // Credit text to be displayed
      url: '', // (Optional) URL link to the original artwork or artist's page
    },
  },
  favicon: [
    // Leave this array empty to use the default favicon
    {
      src: '/favicon/favicon.ico', // Path of the favicon, relative to the /public directory
      // theme: 'light', // (Optional) Either 'light' or 'dark', set only if you have different favicons for light and dark mode
      // sizes: '32x32', // (Optional) Size of the favicon, set only if you have favicons of different sizes
    },
  ],
};

export const navBarConfig: NavBarConfig = {
  links: [
    LinkPreset.Home,
    LinkPreset.Archive,
    LinkPreset.About,
    {
      name: 'GitHub',
      url: 'https://github.com/sphere-bit/toycube-fuwari-blog', // Internal links should not include the base path, as it is automatically added
      external: true, // Show an external link icon and will open in a new tab
    },
  ],
};

export const profileConfig: ProfileConfig = {
  avatar: 'assets/images/demo-avatar.png', // Relative to the /src directory. Relative to the /public directory if it starts with '/'
  name: 'Toycube',
  bio: 'Tech enthusiast and digital artist who loves creating both code and art to bring ideas to life.',
  links: [
    {
      name: 'Etsy',
      icon: 'fa6-brands:etsy', // Visit https://icones.js.org/ for icon codes
      // You will need to install the corresponding icon set if it's not already included
      // `pnpm add @iconify-json/<icon-set-name>`
      url: 'https://www.etsy.com/au/shop/PlopBird',
    },
    {
      name: 'eBay',
      icon: 'fa6-brands:ebay',
      url: 'https://www.ebay.com.au/usr/toycube',
    },
    {
      name: 'GitHub',
      icon: 'fa6-brands:github',
      url: 'https://github.com/sphere-bit/toycube-fuwari-blog',
    },
    {
      name: 'Pinterest',
      icon: 'fa6-brands:pinterest',
      url: 'https://au.pinterest.com/PlopBird/',
    },
    {
      name: 'Deviantart',
      icon: 'jam:deviantart',
      url: 'https://www.deviantart.com/dreamup',
    },
    {
      name: 'Shop',
      icon: 'fa6-regular:square-full',
      url: 'https://toycube.fwscart.com/',
    },
  ],
};

export const licenseConfig: LicenseConfig = {
  enable: true,
  name: 'CC BY-NC-SA 4.0',
  url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
};
